name: amir_portfolio
description: Amir Sohail - Senior Flutter Engineer Portfolio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5

  # Navigation
  go_router: ^14.2.7

  # UI & Animations
  animate_do: ^3.3.4
  visibility_detector: ^0.4.0+2
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0

  # Utils
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
